name: Daily Auction Treasury Data Fetch

# when to trigger the script
on:
  schedule:
    # this runs at 00:00 UTC every day (8:00 am Perth time)
    - cron: '0 0 * * *'
  workflow_dispatch: # button for manually testing

jobs:
  build:
    runs-on: ubuntu-latest # virtual machine with (Linux)Ubuntu operating system

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/checkout@v3
      with:
        python-version: '3.11' # install python into virtual machine
      
      # install libraries
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests urllib3 
        pip install gspread google-auth pandas requests

    - name: Run Fetch Script
      run: python fetch_data/fetch_data.py

    - name: Commit and Push changes
      # this part "saves" the new csv back to github repo automatically
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add fetch_data/US_Auction_Data.csv
        git commit -m "Auto-update: New Treasury Auction Data" || echo "No changes to commit"
        git push